#!/bin/bash
# Mapping script for Cre transgene verification
REFERENCE="references/cre.fa"
FASTQ_DIR="fastq"
OUT="results/cre_mapping"

mkdir -p references $OUT

# Create Cre Reference
if [ ! -f "$REFERENCE" ]; then
cat <<EOF > "$REFERENCE"
>Cre
AAGCTTGTCCACCATGGTGCCCAAGAAGAAGAGGAAAGTCTCCAACCTGCTGACTGTGCACCAAAACCTG
CCTGCCCTCCCTGTGGATGCCACCTCTGATGAAGTCAGGAAGAACCTGATGGACATGTTCAGGGACAGGC
AGGCCTTCTCTGAACACACCTGGAAGATGCTCCTGTCTGTGTGCAGATCCTGGGCTGCCTGGTGCAAGCT
GAACAACAGGAAATGGTTCCCTGCTGAACCTGAGGATGTGAGGGACTACCTCCTGTACCTGCAAGCCAGA
GGCCTGGCTGTGAAGACCATCCAACAGCACCTGGGCCAGCTCAACATGCTGCACAGGAGATCTGGCCTGC
CTCGCCCTTCTGACTCCAATGCTGTGTCCCTGGTGATGAGGAGAATCAGAAAGGAGAATGTGGATGCTGG
GGAGAGAGCCAAGCAGGCCCTGGCCTTTGAACGCACTGACTTTGACCAAGTCAGATCCCTGATGGAGAAC
TCTGACAGATGCCAGGACATCAGGAACCTGGCCTTCCTGGGCATTGCCTACAACACCCTGCTGCGCATTG
CCGAAATTGCCAGAATCAGAGTGAAGGACATCTCCCGCACCGATGGTGGGAGAATGCTGATCCACATTGG
CAGGACCAAGACCCTGGTGTCCACAGCTGGTGTGGAGAAGGCCCTGTCCCTGGGGGTTACCAAGCTGGTG
GAGAGATGGATCTCTGTGTCTGGTGTGGCTGATGACCCCAACAACTACCTGTTCTGCCGGGTCAGAAAGA
ATGGTGTGGCTGCCCCTTCTGCCACCTCCCAACTGTCCACCCGGGCCCTGGAAGGGATCTTTGAGGCCAC
CCACCGCCTGATCTATGGTGCCAAGGATGACTCTGGGCAGAGATACCTGGCCTGGTCTGGCCACTCTGCC
AGAGTGGGTGCTGCCAGGGACATGGCCAGGGCTGGTGTGTCCATCCCTGAAATCATGCAGGCTGGTGGCT
GGACCAATGTGAACATAGTGATGAACTACATCAGAAACCTGGACTCTGAGACTGGGGCCATGGTGAGGCT
GCTCGAGGATGGGGACTGAAACTGAGTCGA
EOF
bwa index $REFERENCE
fi

echo -e "Sample\tRPM" > $OUT/summary.tsv

for R1 in $FASTQ_DIR/*_R1_001.fastq.gz; do
    SAMPLE=$(basename $R1 _R1_001.fastq.gz)
    R2="${R1/_R1_001.fastq.gz/_R2_001.fastq.gz}"
    
    # Align and Calculate RPM
    bwa mem $REFERENCE $R1 $R2 | samtools view -bS | samtools sort -o $OUT/${SAMPLE}.bam
    TOTAL=$(zcat $R1 $R2 | wc -l); TOTAL=$((TOTAL / 4))
    MAPPED=$(samtools view -c -F 4 $OUT/${SAMPLE}.bam)
    RPM=$(echo "scale=6; $MAPPED * 1000000 / $TOTAL" | bc)
    
    echo -e "${SAMPLE}\t${RPM}" >> $OUT/summary.tsv
done
